add_test([=[MyPluginTest.PlaceholderTest]=]  /home/runner/work/clap-jules/clap-jules/build-skia/my_plugin_tests [==[--gtest_filter=MyPluginTest.PlaceholderTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyPluginTest.PlaceholderTest]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/clap-jules/clap-jules/build-skia SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GraphicsTest.GraphicsContextCreation]=]  /home/runner/work/clap-jules/clap-jules/build-skia/my_plugin_tests [==[--gtest_filter=GraphicsTest.GraphicsContextCreation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GraphicsTest.GraphicsContextCreation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/clap-jules/clap-jules/build-skia SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GraphicsTest.BasicDrawingOperations]=]  /home/runner/work/clap-jules/clap-jules/build-skia/my_plugin_tests [==[--gtest_filter=GraphicsTest.BasicDrawingOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GraphicsTest.BasicDrawingOperations]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/clap-jules/clap-jules/build-skia SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GraphicsTest.SkiaAvailabilityCheck]=]  /home/runner/work/clap-jules/clap-jules/build-skia/my_plugin_tests [==[--gtest_filter=GraphicsTest.SkiaAvailabilityCheck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GraphicsTest.SkiaAvailabilityCheck]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/clap-jules/clap-jules/build-skia SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  my_plugin_tests_TESTS MyPluginTest.PlaceholderTest GraphicsTest.GraphicsContextCreation GraphicsTest.BasicDrawingOperations GraphicsTest.SkiaAvailabilityCheck)
