name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
 # push:
   # paths:
   #   - .github/workflows/copilot-setup-steps.yml
 # pull_request:
  #  paths:
   #   - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install basic development dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            pkg-config \
            qt6-base-dev \
            libqt6core6t64 \
            libqt6widgets6t64

      - name: Clone CLAP host repository
        run: |
          git clone --recursive https://github.com/free-audio/clap-host.git /tmp/clap-host

      - name: Setup vcpkg (if needed for advanced building)
        working-directory: /tmp/clap-host
        run: |
          # Bootstrap vcpkg for potential future use
          vcpkg/bootstrap-vcpkg.sh

      - name: Verify CLAP host environment setup 
        working-directory: /tmp/clap-host
        run: |
          echo "CLAP Host repository cloned successfully"
          echo "Directory contents:"
          ls -la
          echo ""
          echo "CMake presets available:"
          cmake --list-presets=configure | grep -E "(ninja|vcpkg)" || echo "No presets found - using basic cmake"
          echo ""
          echo "CLAP SDK version:"
          grep -r "define CLAP_VERSION" clap/include/clap/version.h || echo "Version info not found"
          echo ""
          echo "Environment ready for CLAP host development"

      - name: Optional build attempt (may fail due to dependency versions)
        working-directory: /tmp/clap-host
        continue-on-error: true
        run: |
          echo "Attempting basic configuration test..."
          # Try to configure - this may fail but helps validate the setup
          cmake --preset ninja-system > /dev/null 2>&1 && echo "✓ Configuration successful" || echo "✗ Configuration failed (expected for system libraries)"