name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: clap-host-linux-${{ github.sha }}
          path: |
            clap-host/builds/ninja-vcpkg/host/Release/clap-host

      - name: Check if artifact exists
        id: check_artifact
        run: |
          if [ -d ./build ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Install system dependencies for clap-host (vcpkg build)
        if: steps.check_artifact.outputs.found == 'false'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gperf \
            ninja-build \
            cmake \
            git \
            curl \
            zip \
            unzip \
            tar \
            pkg-config \
            libatspi2.0-dev \
            libfontconfig1-dev \
            libfreetype-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libx11-xcb-dev \
            autoconf \
            libtool \
            libxcb-damage0-dev \
            libxcb-dpms0-dev \
            libxcb-glx0-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-present-dev \
            libxcb-randr0-dev \
            libxcb-record0-dev \
            libxcb-render-util0-dev \
            libxcb-render0-dev \
            libxcb-res0-dev \
            libxcb-shape0-dev \
            libxcb-shm0-dev \
            libxcb-sync0-dev \
            libxcb-util-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libxcb1-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libxrender-dev \
            qt6-base-dev

      - name: Clone clap-host repository
        if: steps.check_artifact.outputs.found == 'false'
        run: |
          git clone --recurse-submodules https://github.com/free-audio/clap-host.git clap-host

      - name: Build clap-host using vcpkg
        if: steps.check_artifact.outputs.found == 'false'
        run: |
          cd clap-host
          # Bootstrap vcpkg
          vcpkg/bootstrap-vcpkg.sh
          # Build using the clap-host build script
          scripts/build.sh

      - name: Upload clap-host artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clap-host-linux-${{ github.sha }}
          path: |
            clap-host/builds/ninja-vcpkg/host/Release/clap-host
          if-no-files-found: warn
