name: Copilot Setup Steps

# Environment setup for GitHub Copilot Coding Agent
# This file configures the development environment with necessary tools and dependencies

steps:
  # Install development dependencies for Linux environments
  - name: Install dependencies (Linux)
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        ninja-build \
        cmake \
        git \
        build-essential \
        pkg-config \
        libasound2-dev \
        curl

  # Install development dependencies for Windows environments  
  - name: Install dependencies (Windows)
    if: runner.os == 'Windows'
    run: |
      choco install ninja cmake git -y
    shell: powershell

  # Set up the repository with submodules
  - name: Initialize repository
    run: |
      git submodule update --init --recursive

  # Build the clap-jules plugin to verify environment setup
  - name: Build clap-jules plugin
    run: |
      cmake . -B build
      cmake --build build --config Release