name: Build CLAP Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Set Git safe directory
        run: git config --global --add safe.directory '*'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up MSVC build tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: 'x64' # Assuming 64-bit build, can be adjusted

      - name: Build Skia
        shell: cmd
        run: |
          cd skia
          python tools/git-sync-deps
          bin/gn gen out/Release --args="is_official_build=true skia_use_system_libraries=false skia_use_libwebp=false skia_use_libjpeg_turbo=false skia_use_libpng=false skia_use_expat=false skia_use_freetype=true skia_enable_fontmgr_custom_directory=false skia_enable_fontmgr_custom_embedded=false skia_enable_fontmgr_custom_empty=true skia_use_harfbuzz=false"
          ninja -C out/Release skia skshaper skparagraph
          cd ..

      - name: Clean previous build artifacts
        run: |
          if (Test-Path build) {
            Remove-Item -Recurse -Force build
          }
          if (Test-Path CMakeCache.txt) {
            Remove-Item CMakeCache.txt
          }
        shell: pwsh

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload CLAP plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: clap-plugin-windows
          path: build/Release/*.clap # Assuming the plugin is in build/Release and has a .clap extension
          if-no-files-found: error # Fail the workflow if the plugin isn't found
